// paises.js - Lista de países con códigos ISO para banderas
const paises = [
    { nombre: 'Afganistán', iso: 'AF' },
    { nombre: 'Albania', iso: 'AL' },
    { nombre: 'Alemania', iso: 'DE' },
    { nombre: 'Andorra', iso: 'AD' },
    { nombre: 'Angola', iso: 'AO' },
    { nombre: 'Antigua y Barbuda', iso: 'AG' },
    { nombre: 'Arabia Saudita', iso: 'SA' },
    { nombre: 'Argelia', iso: 'DZ' },
    { nombre: 'Argentina', iso: 'AR' },
    { nombre: 'Armenia', iso: 'AM' },
    { nombre: 'Australia', iso: 'AU' },
    { nombre: 'Austria', iso: 'AT' },
    { nombre: 'Azerbaiyán', iso: 'AZ' },
    { nombre: 'Bahamas', iso: 'BS' },
    { nombre: 'Bangladés', iso: 'BD' },
    { nombre: 'Barbados', iso: 'BB' },
    { nombre: 'Baréin', iso: 'BH' },
    { nombre: 'Bélgica', iso: 'BE' },
    { nombre: 'Belice', iso: 'BZ' },
    { nombre: 'Benín', iso: 'BJ' },
    { nombre: 'Bielorrusia', iso: 'BY' },
    { nombre: 'Birmania', iso: 'MM' },
    { nombre: 'Bolivia', iso: 'BO' },
    { nombre: 'Bosnia y Herzegovina', iso: 'BA' },
    { nombre: 'Botsuana', iso: 'BW' },
    { nombre: 'Brasil', iso: 'BR' },
    { nombre: 'Brunéi', iso: 'BN' },
    { nombre: 'Bulgaria', iso: 'BG' },
    { nombre: 'Burkina Faso', iso: 'BF' },
    { nombre: 'Burundi', iso: 'BI' },
    { nombre: 'Bután', iso: 'BT' },
    { nombre: 'Cabo Verde', iso: 'CV' },
    { nombre: 'Camboya', iso: 'KH' },
    { nombre: 'Camerún', iso: 'CM' },
    { nombre: 'Canadá', iso: 'CA' },
    { nombre: 'Catar', iso: 'QA' },
    { nombre: 'Chad', iso: 'TD' },
    { nombre: 'Chile', iso: 'CL' },
    { nombre: 'China', iso: 'CN' },
    { nombre: 'Chipre', iso: 'CY' },
    { nombre: 'Colombia', iso: 'CO' },
    { nombre: 'Comoras', iso: 'KM' },
    { nombre: 'Corea del Norte', iso: 'KP' },
    { nombre: 'Corea del Sur', iso: 'KR' },
    { nombre: 'Costa de Marfil', iso: 'CI' },
    { nombre: 'Costa Rica', iso: 'CR' },
    { nombre: 'Croacia', iso: 'HR' },
    { nombre: 'Cuba', iso: 'CU' },
    { nombre: 'Dinamarca', iso: 'DK' },
    { nombre: 'Dominica', iso: 'DM' },
    { nombre: 'Ecuador', iso: 'EC' },
    { nombre: 'Egipto', iso: 'EG' },
    { nombre: 'El Salvador', iso: 'SV' },
    { nombre: 'Emiratos Árabes Unidos', iso: 'AE' },
    { nombre: 'Eritrea', iso: 'ER' },
    { nombre: 'Eslovaquia', iso: 'SK' },
    { nombre: 'Eslovenia', iso: 'SI' },
    { nombre: 'España', iso: 'ES' },
    { nombre: 'Estados Unidos', iso: 'US' },
    { nombre: 'Estonia', iso: 'EE' },
    { nombre: 'Etiopía', iso: 'ET' },
    { nombre: 'Filipinas', iso: 'PH' },
    { nombre: 'Finlandia', iso: 'FI' },
    { nombre: 'Fiyi', iso: 'FJ' },
    { nombre: 'Francia', iso: 'FR' },
    { nombre: 'Gabón', iso: 'GA' },
    { nombre: 'Gambia', iso: 'GM' },
    { nombre: 'Georgia', iso: 'GE' },
    { nombre: 'Ghana', iso: 'GH' },
    { nombre: 'Granada', iso: 'GD' },
    { nombre: 'Grecia', iso: 'GR' },
    { nombre: 'Guatemala', iso: 'GT' },
    { nombre: 'Guyana', iso: 'GY' },
    { nombre: 'Guinea', iso: 'GN' },
    { nombre: 'Guinea-Bisáu', iso: 'GW' },
    { nombre: 'Guinea Ecuatorial', iso: 'GQ' },
    { nombre: 'Haití', iso: 'HT' },
    { nombre: 'Honduras', iso: 'HN' },
    { nombre: 'Hungría', iso: 'HU' },
    { nombre: 'India', iso: 'IN' },
    { nombre: 'Indonesia', iso: 'ID' },
    { nombre: 'Irak', iso: 'IQ' },
    { nombre: 'Irán', iso: 'IR' },
    { nombre: 'Irlanda', iso: 'IE' },
    { nombre: 'Islandia', iso: 'IS' },
    { nombre: 'Islas Marshall', iso: 'MH' },
    { nombre: 'Islas Salomón', iso: 'SB' },
    { nombre: 'Israel', iso: 'IL' },
    { nombre: 'Italia', iso: 'IT' },
    { nombre: 'Jamaica', iso: 'JM' },
    { nombre: 'Japón', iso: 'JP' },
    { nombre: 'Jordania', iso: 'JO' },
    { nombre: 'Kazajistán', iso: 'KZ' },
    { nombre: 'Kenia', iso: 'KE' },
    { nombre: 'Kirguistán', iso: 'KG' },
    { nombre: 'Kiribati', iso: 'KI' },
    { nombre: 'Kuwait', iso: 'KW' },
    { nombre: 'Laos', iso: 'LA' },
    { nombre: 'Lesoto', iso: 'LS' },
    { nombre: 'Letonia', iso: 'LV' },
    { nombre: 'Líbano', iso: 'LB' },
    { nombre: 'Liberia', iso: 'LR' },
    { nombre: 'Libia', iso: 'LY' },
    { nombre: 'Liechtenstein', iso: 'LI' },
    { nombre: 'Lituania', iso: 'LT' },
    { nombre: 'Luxemburgo', iso: 'LU' },
    { nombre: 'Macedonia del Norte', iso: 'MK' },
    { nombre: 'Madagascar', iso: 'MG' },
    { nombre: 'Malasia', iso: 'MY' },
    { nombre: 'Malaui', iso: 'MW' },
    { nombre: 'Maldivas', iso: 'MV' },
    { nombre: 'Malí', iso: 'ML' },
    { nombre: 'Malta', iso: 'MT' },
    { nombre: 'Marruecos', iso: 'MA' },
    { nombre: 'Mauricio', iso: 'MU' },
    { nombre: 'Mauritania', iso: 'MR' },
    { nombre: 'México', iso: 'MX' },
    { nombre: 'Micronesia', iso: 'FM' },
    { nombre: 'Moldavia', iso: 'MD' },
    { nombre: 'Mónaco', iso: 'MC' },
    { nombre: 'Mongolia', iso: 'MN' },
    { nombre: 'Montenegro', iso: 'ME' },
    { nombre: 'Mozambique', iso: 'MZ' },
    { nombre: 'Namibia', iso: 'NA' },
    { nombre: 'Nauru', iso: 'NR' },
    { nombre: 'Nepal', iso: 'NP' },
    { nombre: 'Nicaragua', iso: 'NI' },
    { nombre: 'Níger', iso: 'NE' },
    { nombre: 'Nigeria', iso: 'NG' },
    { nombre: 'Noruega', iso: 'NO' },
    { nombre: 'Nueva Zelanda', iso: 'NZ' },
    { nombre: 'Omán', iso: 'OM' },
    { nombre: 'Países Bajos', iso: 'NL' },
    { nombre: 'Pakistán', iso: 'PK' },
    { nombre: 'Palaos', iso: 'PW' },
    { nombre: 'Palestina', iso: 'PS' },
    { nombre: 'Panamá', iso: 'PA' },
    { nombre: 'Papúa Nueva Guinea', iso: 'PG' },
    { nombre: 'Paraguay', iso: 'PY' },
    { nombre: 'Perú', iso: 'PE' },
    { nombre: 'Polonia', iso: 'PL' },
    { nombre: 'Portugal', iso: 'PT' },
    { nombre: 'Reino Unido', iso: 'GB' },
    { nombre: 'República Centroafricana', iso: 'CF' },
    { nombre: 'República Checa', iso: 'CZ' },
    { nombre: 'República del Congo', iso: 'CG' },
    { nombre: 'República Democrática del Congo', iso: 'CD' },
    { nombre: 'República Dominicana', iso: 'DO' },
    { nombre: 'Ruanda', iso: 'RW' },
    { nombre: 'Rumanía', iso: 'RO' },
    { nombre: 'Rusia', iso: 'RU' },
    { nombre: 'Samoa', iso: 'WS' },
    { nombre: 'San Cristóbal y Nieves', iso: 'KN' },
    { nombre: 'San Marino', iso: 'SM' },
    { nombre: 'San Vicente y las Granadinas', iso: 'VC' },
    { nombre: 'Santa Lucía', iso: 'LC' },
    { nombre: 'Santo Tomé y Príncipe', iso: 'ST' },
    { nombre: 'Senegal', iso: 'SN' },
    { nombre: 'Serbia', iso: 'RS' },
    { nombre: 'Seychelles', iso: 'SC' },
    { nombre: 'Sierra Leona', iso: 'SL' },
    { nombre: 'Singapur', iso: 'SG' },
    { nombre: 'Siria', iso: 'SY' },
    { nombre: 'Somalia', iso: 'SO' },
    { nombre: 'Sri Lanka', iso: 'LK' },
    { nombre: 'Suazilandia', iso: 'SZ' },
    { nombre: 'Sudáfrica', iso: 'ZA' },
    { nombre: 'Sudán', iso: 'SD' },
    { nombre: 'Sudán del Sur', iso: 'SS' },
    { nombre: 'Suecia', iso: 'SE' },
    { nombre: 'Suiza', iso: 'CH' },
    { nombre: 'Surinam', iso: 'SR' },
    { nombre: 'Tailandia', iso: 'TH' },
    { nombre: 'Tanzania', iso: 'TZ' },
    { nombre: 'Tayikistán', iso: 'TJ' },
    { nombre: 'Timor Oriental', iso: 'TL' },
    { nombre: 'Togo', iso: 'TG' },
    { nombre: 'Tonga', iso: 'TO' },
    { nombre: 'Trinidad y Tobago', iso: 'TT' },
    { nombre: 'Túnez', iso: 'TN' },
    { nombre: 'Turkmenistán', iso: 'TM' },
    { nombre: 'Turquía', iso: 'TR' },
    { nombre: 'Tuvalu', iso: 'TV' },
    { nombre: 'Ucrania', iso: 'UA' },
    { nombre: 'Uganda', iso: 'UG' },
    { nombre: 'Uruguay', iso: 'UY' },
    { nombre: 'Uzbekistán', iso: 'UZ' },
    { nombre: 'Vanuatu', iso: 'VU' },
    { nombre: 'Venezuela', iso: 'VE' },
    { nombre: 'Vietnam', iso: 'VN' },
    { nombre: 'Yemen', iso: 'YE' },
    { nombre: 'Yibuti', iso: 'DJ' },
    { nombre: 'Zambia', iso: 'ZM' },
    { nombre: 'Zimbabue', iso: 'ZW' }
];
